services:
  owdb:
    container_name: overwatch-db
    restart: always
    build:
      context: datastore
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbstore:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

  owsync:
    container_name: overwatch-sync
    restart: on-failure:2
    build:
      context: syncservice
    depends_on:
      - owdb
    env_file:
      - .env

  owbackend:
    container_name: overwatch-backend
    restart: always
    build:
      context: backend
    depends_on:
      - owdb
      - owsync
    env_file:
      - .env
    ports:
      - '8573:8573'
    expose:
      - '8573'

volumes:
  dbstore: